### ISSUE TITLE
Angular is not defined

### ISSUE THREAD

**Issue by dev-clavis** [Chimaytric/CharacterSheetManager#2]
Evertime I wanted to run the App.js I got this error Message
```
B:\CharacterSheetManager\app.js:3
angular.module('characterSheetmanager', [
^

ReferenceError: angular is not defined
    at Object.<anonymous> (B:\CharacterSheetManager\app.js:3:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

OS: Win 10 x64
Nodejs: 8.1.3
NPM: 5.3.0
I just started > node app

Before I tried this, I installed both servers, which were pointed out by the readme .

**Comment by Chimaytric** [comment]
**I hope this helps :** 

- Did you start both of the servers with the correct parameters ?
- Do you reach the app through localhost:8080 ? (Opening the index.html in your browser doesn't work)
